### ISSUE TITLE
Increase databaseId field size

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#393]
MalaCard link could not be stored in the database due to 'Data too long' error.

```
2019-02-15 13:57:20,403 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Data truncation: Data too long for column 'databaseId' at row 1
org.springframework.batch.item.file.FlatFileParseException: Parsing error at line: 2013 in resource=[URL [file:/chembio/datasets/csdev/VD/ctd2Dashboard/data/subject_data/tissue_sample/tissue_sample_xrefs.txt]], input=[tissue_sample     malignant thyroid stimulating hormone producing pituitary gland neoplasm   MalaCards        /card/malignant_thyroid_stimulating_hormone_producing_neoplasm_of_pituitary_gland]
        at org.springframework.batch.item.file.FlatFileItemReader.doRead(FlatFileItemReader.java:182)
        at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.read(AbstractItemCountingItemStreamItemReader.java:85)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:90)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:150)
        at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:110)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:367)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:105)
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:68)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:386)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:128)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:264)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:367)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:250)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:135)
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:61)
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124)
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:293)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:120)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:48)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:114)
        at gov.nih.nci.ctd2.dashboard.DashboardAdminMain.launchJob(DashboardAdminMain.java:160)
        at gov.nih.nci.ctd2.dashboard.DashboardAdminMain.main(DashboardAdminMain.java:107)
```

**Comment by vdancik** [comment]
Current databaseId (in xref table) size limit is 64, we should increase it to 128
```
+--------------+-------------+------+-----+---------+-------+
| Field        | Type        | Null | Key | Default | Extra |
+--------------+-------------+------+-----+---------+-------+
| databaseId   | varchar(64) | NO   |     | NULL    |       |
| databaseName | varchar(32) | NO   |     | NULL    |       |
| id           | int(11)     | NO   | PRI | NULL    |       |
+--------------+-------------+------+-----+---------+-------+
```

**Comment by kcs3** [comment]
While Malacards in general are working fine, I cannot verify the particular case cited is fixed, as there is not enough information to locate the exact observation.  For  example, there are no matches to "pituitary" in the Dashboard.

**Comment by vdancik** [comment]
I will add 'too long' entries back to the next data-load package. Then we should be able to verify that this issue is fixed.

**Comment by kcs3** [comment]
Vlado can you verify this is fixed in production?

**Comment by vdancik** [comment]
This issue is fixed: "malignant thyroid stimulating hormone producing pituitary gland neoplasm" disease page (https://ctd2-dashboard.nci.nih.gov/dashboard/#tissue/c5965) now has a MalaCards link https://www.malacards.org/card/malignant_thyroid_stimulating_hormone_producing_neoplasm_of_pituitary_gland
